env: prod
http:
  host: 0.0.0.0
  port: 5001
security:
  jwt:
    key: change-me-in-production
  auth:
    mode: jwt
    proxy:
      username_header: X-Forwarded-User
      auto_provision: true
dockge:
  stacks_dir: storage/stacks
data:
  db:
    user:
      dsn: storage/dockge.db
log:
  log_level: info
  mode: both
  encoding: json
  log_file_name: "./storage/logs/dockge.log"
  max_backups: 30
  max_age: 28
  max_size: 1024
  compress: true
